// **********************************************************************
// Parsed By TarsParser(2.4.5), Generated By tars2node(20200707)
// TarsParser Maintained By <TARS> and tars2node Maintained By <superzheng>
// Generated from "Process.tars" by Client Mode
// **********************************************************************

/* eslint-disable */

"use strict";

var assert    = require("assert");
var TarsStream = require("@tars/stream");
var TarsError  = require("@tars/rpc").error;

var _hasOwnProperty = Object.prototype.hasOwnProperty;
var _makeError = function (data, message, type) {
    var error = new Error(message || "");
    error.request = data.request;
    error.response = {
        "costtime" : data.request.costtime
    };
    if (type === TarsError.CLIENT.DECODE_ERROR) {
        error.name = "DECODE_ERROR";
        error.response.error = {
            "code" : type,
            "message" : message
        };
    } else {
        error.name = "RPC_ERROR";
        error.response.error = data.error;
    }
    return error;
};

var civetTenantCenter = civetTenantCenter || {};
module.exports.civetTenantCenter = civetTenantCenter;

civetTenantCenter.ProcessProxy = function () {
    this._name    = undefined;
    this._worker  = undefined;
};

civetTenantCenter.ProcessProxy.prototype.setTimeout = function (iTimeout) {
    this._worker.timeout = iTimeout;
};

civetTenantCenter.ProcessProxy.prototype.getTimeout = function () {
    return this._worker.timeout;
};

civetTenantCenter.ProcessProxy.prototype.setVersion = function (iVersion) {
    this._worker.version = iVersion;
};

civetTenantCenter.ProcessProxy.prototype.getVersion = function () {
    return this._worker.version;
};

civetTenantCenter.UserAuthDataInfo = function() {
    this.username = "";
    this.password = "";
    this.companyID = "";
    this.phone = "";
    this.wechat = "";
    this.verifyCode = "";
    this.logintype = "";
    this._classname = "civetTenantCenter.UserAuthDataInfo";
};
civetTenantCenter.UserAuthDataInfo._classname = "civetTenantCenter.UserAuthDataInfo";
civetTenantCenter.UserAuthDataInfo._write = function (os, tag, value) { os.writeStruct(tag, value); };
civetTenantCenter.UserAuthDataInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
civetTenantCenter.UserAuthDataInfo._readFrom = function (is) {
    var tmp = new civetTenantCenter.UserAuthDataInfo;
    tmp.username = is.readString(0, false, "");
    tmp.password = is.readString(1, false, "");
    tmp.companyID = is.readString(2, false, "");
    tmp.phone = is.readString(3, false, "");
    tmp.wechat = is.readString(4, false, "");
    tmp.verifyCode = is.readString(5, false, "");
    tmp.logintype = is.readString(6, false, "");
    return tmp;
};
civetTenantCenter.UserAuthDataInfo.prototype._writeTo = function (os) {
    os.writeString(0, this.username);
    os.writeString(1, this.password);
    os.writeString(2, this.companyID);
    os.writeString(3, this.phone);
    os.writeString(4, this.wechat);
    os.writeString(5, this.verifyCode);
    os.writeString(6, this.logintype);
};
civetTenantCenter.UserAuthDataInfo.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
civetTenantCenter.UserAuthDataInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
civetTenantCenter.UserAuthDataInfo.prototype.toObject = function() { 
    return {
        "username" : this.username,
        "password" : this.password,
        "companyID" : this.companyID,
        "phone" : this.phone,
        "wechat" : this.wechat,
        "verifyCode" : this.verifyCode,
        "logintype" : this.logintype
    };
};
civetTenantCenter.UserAuthDataInfo.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "username") && (this.username = json.username);
    _hasOwnProperty.call(json, "password") && (this.password = json.password);
    _hasOwnProperty.call(json, "companyID") && (this.companyID = json.companyID);
    _hasOwnProperty.call(json, "phone") && (this.phone = json.phone);
    _hasOwnProperty.call(json, "wechat") && (this.wechat = json.wechat);
    _hasOwnProperty.call(json, "verifyCode") && (this.verifyCode = json.verifyCode);
    _hasOwnProperty.call(json, "logintype") && (this.logintype = json.logintype);
    return this;
};
civetTenantCenter.UserAuthDataInfo.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
civetTenantCenter.UserAuthDataInfo.new = function () {
    return new civetTenantCenter.UserAuthDataInfo();
};
civetTenantCenter.UserAuthDataInfo.create = function (is) {
    return civetTenantCenter.UserAuthDataInfo._readFrom(is);
};

var __civetTenantCenter_Process$checkToken$IF = {
    "name" : "checkToken",
    "return" : "int32",
    "arguments" : [{
        "name" : "companyID",
        "class" : "int32",
        "direction" : "in"
    }, {
        "name" : "token",
        "class" : "string",
        "direction" : "in"
    }, {
        "name" : "result",
        "class" : "bool",
        "direction" : "out"
    }]
};

var __civetTenantCenter_Process$checkToken$IE = function (companyID, token) {
    var os = new TarsStream.TarsOutputStream();
    os.writeInt32(1, companyID);
    os.writeString(2, token);
    return os.getBinBuffer();
};

var __civetTenantCenter_Process$checkToken$ID = function (data) {
    try {
        var is = new TarsStream.TarsInputStream(data.response.sBuffer);
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : is.readInt32(0, true, 0),
                "arguments" : {
                    "result" : is.readBoolean(3, true, true)
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __civetTenantCenter_Process$checkToken$PE = function (companyID, token, __$PROTOCOL$VERSION) {
    var tup = new TarsStream.UniAttribute();
    tup.tupVersion = __$PROTOCOL$VERSION;
    tup.writeInt32("companyID", companyID);
    tup.writeString("token", token);
    return tup;
};

var __civetTenantCenter_Process$checkToken$PD = function (data) {
    try {
        var tup = data.response.tup;
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : tup.readInt32("", 0),
                "arguments" : {
                    "result" : tup.readBoolean("result")
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __civetTenantCenter_Process$checkToken$ER = function (data) {
    throw _makeError(data, "Call Process::checkToken failed");
};

civetTenantCenter.ProcessProxy.prototype.checkToken = function (companyID, token) {
    var version = this._worker.version;
    if (version === TarsStream.Tup.TUP_SIMPLE || version === TarsStream.Tup.TUP_COMPLEX) {
        return this._worker.tup_invoke("checkToken", __civetTenantCenter_Process$checkToken$PE(companyID, token, version), arguments[arguments.length - 1], __civetTenantCenter_Process$checkToken$IF).then(__civetTenantCenter_Process$checkToken$PD, __civetTenantCenter_Process$checkToken$ER);
    } else {
        return this._worker.tars_invoke("checkToken", __civetTenantCenter_Process$checkToken$IE(companyID, token), arguments[arguments.length - 1], __civetTenantCenter_Process$checkToken$IF).then(__civetTenantCenter_Process$checkToken$ID, __civetTenantCenter_Process$checkToken$ER);
    }
};
civetTenantCenter.ProcessProxy.checkToken = __civetTenantCenter_Process$checkToken$IF;

var __civetTenantCenter_Process$login$IF = {
    "name" : "login",
    "return" : "int32",
    "arguments" : [{
        "name" : "info",
        "class" : "civetTenantCenter.UserAuthDataInfo",
        "direction" : "in"
    }, {
        "name" : "result",
        "class" : "int32",
        "direction" : "out"
    }, {
        "name" : "token",
        "class" : "string",
        "direction" : "out"
    }]
};

var __civetTenantCenter_Process$login$IE = function (info) {
    var os = new TarsStream.TarsOutputStream();
    os.writeStruct(1, info);
    return os.getBinBuffer();
};

var __civetTenantCenter_Process$login$ID = function (data) {
    try {
        var is = new TarsStream.TarsInputStream(data.response.sBuffer);
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : is.readInt32(0, true, 0),
                "arguments" : {
                    "result" : is.readInt32(2, true, 0),
                    "token" : is.readString(3, true, "")
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __civetTenantCenter_Process$login$PE = function (info, __$PROTOCOL$VERSION) {
    var tup = new TarsStream.UniAttribute();
    tup.tupVersion = __$PROTOCOL$VERSION;
    tup.writeStruct("info", info);
    return tup;
};

var __civetTenantCenter_Process$login$PD = function (data) {
    try {
        var tup = data.response.tup;
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : tup.readInt32("", 0),
                "arguments" : {
                    "result" : tup.readInt32("result"),
                    "token" : tup.readString("token")
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __civetTenantCenter_Process$login$ER = function (data) {
    throw _makeError(data, "Call Process::login failed");
};

civetTenantCenter.ProcessProxy.prototype.login = function (info) {
    var version = this._worker.version;
    if (version === TarsStream.Tup.TUP_SIMPLE || version === TarsStream.Tup.TUP_COMPLEX) {
        return this._worker.tup_invoke("login", __civetTenantCenter_Process$login$PE(info, version), arguments[arguments.length - 1], __civetTenantCenter_Process$login$IF).then(__civetTenantCenter_Process$login$PD, __civetTenantCenter_Process$login$ER);
    } else {
        return this._worker.tars_invoke("login", __civetTenantCenter_Process$login$IE(info), arguments[arguments.length - 1], __civetTenantCenter_Process$login$IF).then(__civetTenantCenter_Process$login$ID, __civetTenantCenter_Process$login$ER);
    }
};
civetTenantCenter.ProcessProxy.login = __civetTenantCenter_Process$login$IF;

var __civetTenantCenter_Process$loginByPhone$IF = {
    "name" : "loginByPhone",
    "return" : "int32",
    "arguments" : [{
        "name" : "companyID",
        "class" : "int32",
        "direction" : "in"
    }, {
        "name" : "info",
        "class" : "civetTenantCenter.UserAuthDataInfo",
        "direction" : "in"
    }, {
        "name" : "result",
        "class" : "int32",
        "direction" : "out"
    }]
};

var __civetTenantCenter_Process$loginByPhone$IE = function (companyID, info) {
    var os = new TarsStream.TarsOutputStream();
    os.writeInt32(1, companyID);
    os.writeStruct(2, info);
    return os.getBinBuffer();
};

var __civetTenantCenter_Process$loginByPhone$ID = function (data) {
    try {
        var is = new TarsStream.TarsInputStream(data.response.sBuffer);
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : is.readInt32(0, true, 0),
                "arguments" : {
                    "result" : is.readInt32(3, true, 0)
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __civetTenantCenter_Process$loginByPhone$PE = function (companyID, info, __$PROTOCOL$VERSION) {
    var tup = new TarsStream.UniAttribute();
    tup.tupVersion = __$PROTOCOL$VERSION;
    tup.writeInt32("companyID", companyID);
    tup.writeStruct("info", info);
    return tup;
};

var __civetTenantCenter_Process$loginByPhone$PD = function (data) {
    try {
        var tup = data.response.tup;
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : tup.readInt32("", 0),
                "arguments" : {
                    "result" : tup.readInt32("result")
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __civetTenantCenter_Process$loginByPhone$ER = function (data) {
    throw _makeError(data, "Call Process::loginByPhone failed");
};

civetTenantCenter.ProcessProxy.prototype.loginByPhone = function (companyID, info) {
    var version = this._worker.version;
    if (version === TarsStream.Tup.TUP_SIMPLE || version === TarsStream.Tup.TUP_COMPLEX) {
        return this._worker.tup_invoke("loginByPhone", __civetTenantCenter_Process$loginByPhone$PE(companyID, info, version), arguments[arguments.length - 1], __civetTenantCenter_Process$loginByPhone$IF).then(__civetTenantCenter_Process$loginByPhone$PD, __civetTenantCenter_Process$loginByPhone$ER);
    } else {
        return this._worker.tars_invoke("loginByPhone", __civetTenantCenter_Process$loginByPhone$IE(companyID, info), arguments[arguments.length - 1], __civetTenantCenter_Process$loginByPhone$IF).then(__civetTenantCenter_Process$loginByPhone$ID, __civetTenantCenter_Process$loginByPhone$ER);
    }
};
civetTenantCenter.ProcessProxy.loginByPhone = __civetTenantCenter_Process$loginByPhone$IF;

var __civetTenantCenter_Process$loginByWechat$IF = {
    "name" : "loginByWechat",
    "return" : "int32",
    "arguments" : [{
        "name" : "companyID",
        "class" : "int32",
        "direction" : "in"
    }, {
        "name" : "info",
        "class" : "civetTenantCenter.UserAuthDataInfo",
        "direction" : "in"
    }, {
        "name" : "result",
        "class" : "int32",
        "direction" : "out"
    }]
};

var __civetTenantCenter_Process$loginByWechat$IE = function (companyID, info) {
    var os = new TarsStream.TarsOutputStream();
    os.writeInt32(1, companyID);
    os.writeStruct(2, info);
    return os.getBinBuffer();
};

var __civetTenantCenter_Process$loginByWechat$ID = function (data) {
    try {
        var is = new TarsStream.TarsInputStream(data.response.sBuffer);
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : is.readInt32(0, true, 0),
                "arguments" : {
                    "result" : is.readInt32(3, true, 0)
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __civetTenantCenter_Process$loginByWechat$PE = function (companyID, info, __$PROTOCOL$VERSION) {
    var tup = new TarsStream.UniAttribute();
    tup.tupVersion = __$PROTOCOL$VERSION;
    tup.writeInt32("companyID", companyID);
    tup.writeStruct("info", info);
    return tup;
};

var __civetTenantCenter_Process$loginByWechat$PD = function (data) {
    try {
        var tup = data.response.tup;
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : tup.readInt32("", 0),
                "arguments" : {
                    "result" : tup.readInt32("result")
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __civetTenantCenter_Process$loginByWechat$ER = function (data) {
    throw _makeError(data, "Call Process::loginByWechat failed");
};

civetTenantCenter.ProcessProxy.prototype.loginByWechat = function (companyID, info) {
    var version = this._worker.version;
    if (version === TarsStream.Tup.TUP_SIMPLE || version === TarsStream.Tup.TUP_COMPLEX) {
        return this._worker.tup_invoke("loginByWechat", __civetTenantCenter_Process$loginByWechat$PE(companyID, info, version), arguments[arguments.length - 1], __civetTenantCenter_Process$loginByWechat$IF).then(__civetTenantCenter_Process$loginByWechat$PD, __civetTenantCenter_Process$loginByWechat$ER);
    } else {
        return this._worker.tars_invoke("loginByWechat", __civetTenantCenter_Process$loginByWechat$IE(companyID, info), arguments[arguments.length - 1], __civetTenantCenter_Process$loginByWechat$IF).then(__civetTenantCenter_Process$loginByWechat$ID, __civetTenantCenter_Process$loginByWechat$ER);
    }
};
civetTenantCenter.ProcessProxy.loginByWechat = __civetTenantCenter_Process$loginByWechat$IF;

var __civetTenantCenter_Process$logout$IF = {
    "name" : "logout",
    "return" : "int32",
    "arguments" : [{
        "name" : "token",
        "class" : "string",
        "direction" : "in"
    }, {
        "name" : "result",
        "class" : "int32",
        "direction" : "out"
    }]
};

var __civetTenantCenter_Process$logout$IE = function (token) {
    var os = new TarsStream.TarsOutputStream();
    os.writeString(1, token);
    return os.getBinBuffer();
};

var __civetTenantCenter_Process$logout$ID = function (data) {
    try {
        var is = new TarsStream.TarsInputStream(data.response.sBuffer);
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : is.readInt32(0, true, 0),
                "arguments" : {
                    "result" : is.readInt32(2, true, 0)
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __civetTenantCenter_Process$logout$PE = function (token, __$PROTOCOL$VERSION) {
    var tup = new TarsStream.UniAttribute();
    tup.tupVersion = __$PROTOCOL$VERSION;
    tup.writeString("token", token);
    return tup;
};

var __civetTenantCenter_Process$logout$PD = function (data) {
    try {
        var tup = data.response.tup;
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : tup.readInt32("", 0),
                "arguments" : {
                    "result" : tup.readInt32("result")
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __civetTenantCenter_Process$logout$ER = function (data) {
    throw _makeError(data, "Call Process::logout failed");
};

civetTenantCenter.ProcessProxy.prototype.logout = function (token) {
    var version = this._worker.version;
    if (version === TarsStream.Tup.TUP_SIMPLE || version === TarsStream.Tup.TUP_COMPLEX) {
        return this._worker.tup_invoke("logout", __civetTenantCenter_Process$logout$PE(token, version), arguments[arguments.length - 1], __civetTenantCenter_Process$logout$IF).then(__civetTenantCenter_Process$logout$PD, __civetTenantCenter_Process$logout$ER);
    } else {
        return this._worker.tars_invoke("logout", __civetTenantCenter_Process$logout$IE(token), arguments[arguments.length - 1], __civetTenantCenter_Process$logout$IF).then(__civetTenantCenter_Process$logout$ID, __civetTenantCenter_Process$logout$ER);
    }
};
civetTenantCenter.ProcessProxy.logout = __civetTenantCenter_Process$logout$IF;

var __civetTenantCenter_Process$refreshToken$IF = {
    "name" : "refreshToken",
    "return" : "int32",
    "arguments" : [{
        "name" : "companyID",
        "class" : "int32",
        "direction" : "in"
    }, {
        "name" : "oldtoken",
        "class" : "string",
        "direction" : "in"
    }, {
        "name" : "newtoken",
        "class" : "string",
        "direction" : "out"
    }]
};

var __civetTenantCenter_Process$refreshToken$IE = function (companyID, oldtoken) {
    var os = new TarsStream.TarsOutputStream();
    os.writeInt32(1, companyID);
    os.writeString(2, oldtoken);
    return os.getBinBuffer();
};

var __civetTenantCenter_Process$refreshToken$ID = function (data) {
    try {
        var is = new TarsStream.TarsInputStream(data.response.sBuffer);
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : is.readInt32(0, true, 0),
                "arguments" : {
                    "newtoken" : is.readString(3, true, "")
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __civetTenantCenter_Process$refreshToken$PE = function (companyID, oldtoken, __$PROTOCOL$VERSION) {
    var tup = new TarsStream.UniAttribute();
    tup.tupVersion = __$PROTOCOL$VERSION;
    tup.writeInt32("companyID", companyID);
    tup.writeString("oldtoken", oldtoken);
    return tup;
};

var __civetTenantCenter_Process$refreshToken$PD = function (data) {
    try {
        var tup = data.response.tup;
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : tup.readInt32("", 0),
                "arguments" : {
                    "newtoken" : tup.readString("newtoken")
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __civetTenantCenter_Process$refreshToken$ER = function (data) {
    throw _makeError(data, "Call Process::refreshToken failed");
};

civetTenantCenter.ProcessProxy.prototype.refreshToken = function (companyID, oldtoken) {
    var version = this._worker.version;
    if (version === TarsStream.Tup.TUP_SIMPLE || version === TarsStream.Tup.TUP_COMPLEX) {
        return this._worker.tup_invoke("refreshToken", __civetTenantCenter_Process$refreshToken$PE(companyID, oldtoken, version), arguments[arguments.length - 1], __civetTenantCenter_Process$refreshToken$IF).then(__civetTenantCenter_Process$refreshToken$PD, __civetTenantCenter_Process$refreshToken$ER);
    } else {
        return this._worker.tars_invoke("refreshToken", __civetTenantCenter_Process$refreshToken$IE(companyID, oldtoken), arguments[arguments.length - 1], __civetTenantCenter_Process$refreshToken$IF).then(__civetTenantCenter_Process$refreshToken$ID, __civetTenantCenter_Process$refreshToken$ER);
    }
};
civetTenantCenter.ProcessProxy.refreshToken = __civetTenantCenter_Process$refreshToken$IF;



